const API = window.ATTP_API || 'https://so-attp-api.onrender.com';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)]; let state={records:[],inventory:[],menus:[],ocr:null};
function toast(m){const t=$('#toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',3500)}
async function getJwt(){const {data,error}=await authClient.token();if(error||!data?.token)throw new Error('Phiên đăng nhập hết hạn. Hãy đăng nhập lại.');return data.token}
async function api(path,opt={},auth=true){const headers={'content-type':'application/json',...(opt.headers||{})};if(auth)headers.authorization='Bearer '+await getJwt();const r=await fetch(API+path,{...opt,headers});const d=await r.json().catch(()=>({}));if(r.status===401){await showLoggedOut();throw new Error('Phiên đăng nhập hết hạn')};if(!r.ok)throw new Error(d.message||d.error||`HTTP ${r.status}`);return d}
function fmt(d){return d?new Date(d).toLocaleString('vi-VN'):'—'}
async function health(){try{const d=await api('/health',{},false);const bits=[d.dbConfigured?'DB':'',d.storageConfigured?'Storage':'',d.authConfigured?'Auth':'',d.aiConfigured?'AI':''].filter(Boolean);$('#health').textContent=bits.length?bits.join(' + ')+' sẵn sàng':'API đang cấu hình';$('#health').className='pill'}catch{$('#health').textContent='Mất kết nối Neon'}}

async function showLoggedIn(user){state.user=user||null;$('#authGate').classList.add('hidden');$('#appShell').classList.remove('hidden');$('#signOutBtn').classList.remove('hidden');$('#signOutBtn').textContent=user?.email?`Đăng xuất · ${user.email}`:'Đăng xuất';await load()}
async function showLoggedOut(){state.user=null;$('#appShell').classList.add('hidden');$('#signOutBtn').classList.add('hidden');$('#authGate').classList.remove('hidden')}
async function restoreSession(){try{const {data}=await authClient.getSession();if(data?.session&&data?.user)return showLoggedIn(data.user)}catch{}return showLoggedOut()}
function renderAuthMode(){$('#authTitle').textContent=signUpMode?'Tạo tài khoản':'Đăng nhập';$('#authSubmit').textContent=signUpMode?'Tạo tài khoản':'Đăng nhập';$('#authToggle').textContent=signUpMode?'Đã có tài khoản? Đăng nhập':'Chưa có tài khoản? Tạo tài khoản';$('#authPassword').autocomplete=signUpMode?'new-password':'current-password'}
$('#authToggle').onclick=()=>{signUpMode=!signUpMode;renderAuthMode();$('#authMsg').textContent=''};
$('#authForm').onsubmit=async e=>{e.preventDefault();const email=$('#authEmail').value.trim(),password=$('#authPassword').value;$('#authSubmit').disabled=true;$('#authMsg').textContent='Đang xử lý…';try{const result=signUpMode?await authClient.signUp.email({name:email.split('@')[0]||'User',email,password}):await authClient.signIn.email({email,password});if(result.error)throw result.error;const sess=await authClient.getSession();if(sess.data?.user)await showLoggedIn(sess.data.user);else throw new Error('Chưa tạo được phiên đăng nhập');$('#authMsg').textContent=''}catch(err){$('#authMsg').textContent=err?.message||'Không đăng nhập được'}finally{$('#authSubmit').disabled=false}};
$('#signOutBtn').onclick=async()=>{await authClient.signOut();await showLoggedOut()};
\nasync function load(){try{const d=await api('/api/bootstrap');state={...state,...d};render()}catch(e){toast('Không tải được dữ liệu: '+e.message)}}
function render(){
 $('#recordsBody').innerHTML=state.records.map(r=>`<tr><td>${r.id}</td><td>${r.kind}</td><td><span class="badge ${r.status==='ĐÃ XÁC MINH'?'ok':'warn'}">${r.status}</span></td><td>${Object.entries(r.fields||{}).slice(0,4).map(([k,v])=>`${k}: ${v?.value??v}`).join('<br>')}</td><td>${fmt(r.created_at)}</td></tr>`).join('')||'<tr><td colspan="5">Chưa có dữ liệu.</td></tr>';
 $('#inventoryBody').innerHTML=state.inventory.map(x=>{const days=Math.ceil((new Date(x.expiry)-new Date())/86400000);const c=days<0?'bad':days<=7?'warn':'ok';const s=days<0?'QUÁ HẠN':days<=7?'SẮP HẾT HẠN':'CÒN HẠN';return `<tr><td>${x.name}</td><td>${x.in_qty} ${x.unit||''}</td><td>${x.out_qty}</td><td>${x.balance}</td><td>${x.expiry?.slice(0,10)||'—'}</td><td><span class="badge ${c}">${s}</span></td></tr>`}).join('')||'<tr><td colspan="6">Chưa có dữ liệu kho.</td></tr>';
}
$$('#nav button').forEach(b=>b.onclick=()=>{$$('#nav button').forEach(x=>x.classList.toggle('active',x===b));$$('.tab').forEach(t=>t.classList.toggle('active',t.id==='tab-'+b.dataset.tab))});
$('#image').onchange=e=>{const f=e.target.files[0];if(f)$('#preview').src=URL.createObjectURL(f)};
async function fileB64(file,max=1600){const bmp=await createImageBitmap(file);let w=bmp.width,h=bmp.height;const scale=Math.min(1,max/Math.max(w,h),Math.sqrt(2_000_000/(w*h)));w=Math.round(w*scale);h=Math.round(h*scale);const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(bmp,0,0,w,h);const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.9));const data=await new Promise((r,j)=>{const fr=new FileReader();fr.onload=()=>r(fr.result.split(',')[1]);fr.onerror=j;fr.readAsDataURL(blob)});return {data,mimeType:'image/jpeg'}}
$('#runOcr').onclick=async()=>{const f=$('#image').files[0];if(!f)return toast('Hãy chụp/chọn ảnh trước');$('#runOcr').disabled=true;$('#ocrMsg').textContent='Đang đọc 2 lượt và kiểm tra cột…';try{const image=await fileB64(f);state.ocr=await api('/api/ocr',{method:'POST',body:JSON.stringify({kind:$('#kind').value,image})});renderOcr()}catch(e){$('#ocrMsg').textContent=e.message;toast(e.message)}finally{$('#runOcr').disabled=false}}
function renderOcr(){const o=state.ocr;if(!o)return;$('#ocrMsg').textContent=`Đã đọc ${o.passes||2} lượt. Dòng vàng cần dò lại trước khi lưu.`;const fields=(o.fields||[]).map((x,i)=>`<div class="fieldrow"><b>${x.key}</b><input data-fi="${i}" value="${String(x.value).replaceAll('"','&quot;')}"><span class="badge ${x.confidence>=95?'ok':'warn'}">${Math.round(x.confidence)}%</span></div>`).join('');const lines=(o.lineItems||[]).map((x,i)=>`<div class="ocr-line"><input data-ln="${i}" data-k="name" value="${String(x.name).replaceAll('"','&quot;')}"><input data-ln="${i}" data-k="quantity" value="${x.quantity}"><input data-ln="${i}" data-k="unit" value="${x.unit}"><select data-ln="${i}" data-k="kind"><option ${x.kindSuggestion==='1a'?'selected':''}>1a</option><option ${x.kindSuggestion==='1b'?'selected':''}>1b</option><option ${x.kindSuggestion==='review'?'selected':''}>review</option></select><span class="badge ${x.confidence>=95?'ok':'warn'}">${Math.round(x.confidence)}% ${x.columnVerified?'✓ cột':'dò lại'}</span></div>`).join('');$('#ocrResult').innerHTML=`<div class="card"><h3>Trường chung</h3>${fields}<h3>Dòng hàng</h3>${lines||'<p class="muted">Không có bảng hàng.</p>'}<div class="actions"><button class="primary" id="saveOcr">Lưu bản ghi</button></div><details><summary>OCR thô</summary><pre>${o.rawText||''}</pre></details></div>`;$('#saveOcr').onclick=saveOcr}
async function saveOcr(){const o=state.ocr,kind=$('#kind').value;const fields={};(o.fields||[]).forEach((x,i)=>fields[x.key]={value:document.querySelector(`[data-fi="${i}"]`).value,confidence:x.confidence,confirmed:x.confidence>=95});const lines=(o.lineItems||[]).map((x,i)=>{const get=k=>document.querySelector(`[data-ln="${i}"][data-k="${k}"]`).value;return {...x,name:get('name'),quantity:get('quantity'),unit:get('unit'),kind:get('kind')};});try{if((kind==='1a'||kind==='1b')&&lines.length){const usable=lines.filter(x=>['1a','1b'].includes(x.kind));const d=await api('/api/invoice-records',{method:'POST',body:JSON.stringify({sharedFields:fields,lines:usable,rawText:o.rawText,imageKey:o.imageKey,ocrJobId:o.jobId})});toast(`Đã lưu ${d.saved} dòng; ${d.review} dòng cần dò lại`)}else{await api('/api/records',{method:'POST',body:JSON.stringify({kind,fields,rawText:o.rawText,imageKey:o.imageKey,ocrJobId:o.jobId})});toast('Đã lưu bản ghi')}await load()}catch(e){toast('Không lưu được: '+e.message)}}
$('#inventoryForm').onsubmit=async e=>{e.preventDefault();const x=Object.fromEntries(new FormData(e.target));try{await api('/api/inventory',{method:'POST',body:JSON.stringify(x)});toast('Đã nhập kho');e.target.reset();await load()}catch(err){toast(err.message)}};
$('#menuForm').onsubmit=async e=>{e.preventDefault();const x=Object.fromEntries(new FormData(e.target));const items=x.lines.split('\n').map(s=>s.trim()).filter(Boolean).map(line=>{const [dish='',ingredients='',servings='0']=line.split('|').map(s=>s.trim());return {date:x.date,meal:x.meal,dish,ingredients,servings}});try{await api('/api/menu',{method:'POST',body:JSON.stringify({items})});toast('Đã lưu thực đơn');e.target.reset();await load()}catch(err){toast(err.message)}};
$$('[data-period]').forEach(b=>b.onclick=async()=>{try{const d=await api('/api/report?period='+b.dataset.period);$('#reportBox').textContent=`Kỳ: ${d.period}\nBước 1: ${d.step1}\nBước 2: ${d.step2}\nBước 3: ${d.step3}\nMẫu lưu: ${d.samples}\nCần dò OCR: ${d.needs}\nSắp hết hạn: ${d.expiring}\nQuá hạn: ${d.expired}` }catch(e){toast(e.message)}});
health();load();setInterval(health,60000);