import {members as defaultDirectory} from '../../assets/modules/members.js';
import {createAuthStore,authenticate,changePassword} from './auth-service.js';
import {authorizeApi,visibleMemberFields} from './policy.js';
import {createSessionSigner} from './session-token.js';
import {apiEnvelope,apiError} from '../../assets/core/api-contract.js';
const json=(status,body)=>({status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'},body});const ok=(data,status=200)=>json(status,apiEnvelope(data));const fail=(status,code,message='')=>json(status,apiError(code,message));
function bearer(headers={}){const value=headers.authorization||headers.Authorization||'';return/^Bearer\s+(.+)$/i.exec(String(value))?.[1]||null;}
function errorResponse(error){const code=String(error?.message||'internal_error');if(code==='invalid_credentials')return fail(401,code,'MSSV hoặc mật khẩu không đúng.');if(code==='weak_password')return fail(400,code,'Mật khẩu mới chưa đạt yêu cầu tối thiểu.');if(code==='forbidden')return fail(403,code,'Không có quyền thực hiện thao tác này.');if(code==='invalid_token'||code==='expired_token')return fail(401,code,'Phiên đăng nhập không hợp lệ.');return fail(500,'internal_error','Lỗi dịch vụ.');}
export function createApiApp({directory=defaultDirectory,sessionSecret,now=()=>Date.now()}={}){const store=createAuthStore(directory),signer=createSessionSigner(sessionSecret);let theme={primary:'#2d6045',secondary:'#b85f3f',background:'#e9efe4',border:'#315943',radius:18,updatedAt:null,updatedBy:null};const moderationQueue=[];
function identityFromToken(headers={}){const token=bearer(headers);if(!token)throw new Error('invalid_token');const claims=signer.verify(token,now());const account=store.accounts.get(String(claims.mssv||''));if(!account)throw new Error('invalid_token');return{...account.member,authenticated:true};}
function issue(member,mustChangePassword){const token=signer.issue({mssv:member.mssv,role:member.role,name:member.name},now());return{token,member:visibleMemberFields(member,{...member,role:'ADMIN'}),mustChangePassword:Boolean(mustChangePassword)};}
async function handle(request={}){const method=String(request.method||'GET').toUpperCase(),path=String(request.path||'/').split('?')[0],headers=request.headers||{},body=request.body||{};try{
if(method==='GET'&&path==='/api/v1/health')return ok({product:'YHCT SOCIAL',release:'2.5.0',apiVersion:1,status:'ready',memberDirectory:store.accounts.size});
if(method==='POST'&&path==='/api/v1/auth/login'){const result=authenticate(store,{mssv:body.mssv,password:body.password});return ok(issue(result.member,result.mustChangePassword));}
if(method==='POST'&&path==='/api/v1/auth/change-password'){const identity=identityFromToken(headers);return ok(changePassword(store,{mssv:identity.mssv,currentPassword:body.currentPassword,newPassword:body.newPassword}));}
if(method==='GET'&&path==='/api/v1/session'){const identity=identityFromToken(headers),account=store.accounts.get(identity.mssv);return ok({...visibleMemberFields(identity,identity),authenticated:true,mustChangePassword:Boolean(account?.credential?.mustChangePassword)});}
if(method==='GET'&&path==='/api/v1/members'){const identity=identityFromToken(headers);return ok([...store.accounts.values()].map(x=>visibleMemberFields(x.member,identity)));}
if(method==='GET'&&path==='/api/v1/operator/queue'){const identity=identityFromToken(headers);if(!authorizeApi(identity,'operator:queue'))return fail(403,'forbidden');return ok(moderationQueue.map(x=>({...x})));}
if(method==='POST'&&path==='/api/v1/operator/escalate'){const identity=identityFromToken(headers);if(!authorizeApi(identity,'operator:escalate'))return fail(403,'forbidden');const item={id:String(body.id||`q_${now()}`),status:'escalated',escalatedBy:identity.mssv,at:now()};const existing=moderationQueue.findIndex(x=>x.id===item.id);if(existing>=0)moderationQueue[existing]={...moderationQueue[existing],...item};else moderationQueue.push(item);return ok(item);}
if(method==='GET'&&path==='/api/v1/admin/health'){const identity=identityFromToken(headers);if(!authorizeApi(identity,'admin:operate'))return fail(403,'forbidden');return ok({auth:'PASS',roleGuard:'PASS',members:store.accounts.size,theme:'PASS',moderationQueue:moderationQueue.length});}
if(method==='PUT'&&path==='/api/v1/admin/theme'){const identity=identityFromToken(headers);if(!authorizeApi(identity,'admin:theme'))return fail(403,'forbidden');const color=/^#[0-9a-f]{6}$/i,next={...theme};if(body.primary!==undefined){if(!color.test(body.primary))return fail(400,'invalid_theme');next.primary=body.primary;}if(body.secondary!==undefined){if(!color.test(body.secondary))return fail(400,'invalid_theme');next.secondary=body.secondary;}if(body.background!==undefined){if(!color.test(body.background))return fail(400,'invalid_theme');next.background=body.background;}if(body.border!==undefined){if(!color.test(body.border))return fail(400,'invalid_theme');next.border=body.border;}if(body.radius!==undefined){const r=Number(body.radius);if(!Number.isInteger(r)||r<8||r>30)return fail(400,'invalid_theme');next.radius=r;}theme={...next,updatedAt:now(),updatedBy:identity.mssv};return ok({...theme});}
return fail(404,'not_found','Không tìm thấy API route.');}catch(error){return errorResponse(error);}}
return{handle,store,getTheme:()=>({...theme}),getModerationQueue:()=>moderationQueue.map(x=>({...x}))};}
