import {randomBytes,scryptSync,timingSafeEqual} from 'node:crypto';
const DEFAULT_KEYLEN=32,DEFAULT_COST=16384;
function normalizeSalt(salt){if(!salt)return randomBytes(16).toString('hex');const value=String(salt).trim().toLowerCase();if(!/^[0-9a-f]{16,128}$/.test(value))throw new Error('invalid_salt');return value;}
function derive(secret,salt,keylen=DEFAULT_KEYLEN,cost=DEFAULT_COST){return scryptSync(String(secret),Buffer.from(salt,'hex'),keylen,{N:cost,r:8,p:1,maxmem:64*1024*1024}).toString('hex');}
export function createCredential(password,{salt=null,mustChangePassword=true,cost=DEFAULT_COST}={}){const normalizedSalt=normalizeSalt(salt);return{algorithm:'scrypt',salt:normalizedSalt,hash:derive(password,normalizedSalt,DEFAULT_KEYLEN,cost),keylen:DEFAULT_KEYLEN,cost,mustChangePassword:Boolean(mustChangePassword),updatedAt:Date.now()};}
export function verifyCredential(credential,password){if(!credential?.hash||!credential?.salt||credential.algorithm!=='scrypt')return false;const actual=Buffer.from(derive(password,credential.salt,credential.keylen||DEFAULT_KEYLEN,credential.cost||DEFAULT_COST),'hex');const expected=Buffer.from(credential.hash,'hex');return actual.length===expected.length&&timingSafeEqual(actual,expected);}
export function validateNewPassword(password){const value=String(password||'');return value.length>=12&&/[A-Z]/.test(value)&&/[a-z]/.test(value)&&/\d/.test(value)&&/[^A-Za-z0-9]/.test(value);}
export function changeCredential(current,newPassword,{salt=null,cost=DEFAULT_COST}={}){if(!validateNewPassword(newPassword))throw new Error('weak_password');return createCredential(newPassword,{salt,mustChangePassword:false,cost});}
export function createAuthStore(directory=[],options={}){const accounts=new Map();for(const member of directory){const mssv=String(member.mssv||member.id||'').trim();if(!mssv||accounts.has(mssv))continue;accounts.set(mssv,{mssv,member:{...member,id:String(member.id||mssv),mssv},credential:null,initialCredentialPending:true,locked:false,failedAttempts:0,lastLoginAt:null});}return{accounts,options:{...options}};}
function ensureCredential(account,password,store){if(account.credential)return;if(!account.initialCredentialPending||String(password)!==account.mssv)throw new Error('invalid_credentials');const salt=store.options.saltFactory?.(account.member)||null;const cost=store.options.cost||1024;account.credential=createCredential(account.mssv,{salt,mustChangePassword:true,cost});account.initialCredentialPending=false;}
export function authenticate(store,{mssv,password}={}){const id=String(mssv||'').trim(),account=store?.accounts?.get(id);if(!account||account.locked)throw new Error('invalid_credentials');ensureCredential(account,password,store);if(!verifyCredential(account.credential,password)){account.failedAttempts=(account.failedAttempts||0)+1;if(account.failedAttempts>=10)account.locked=true;throw new Error('invalid_credentials');}account.failedAttempts=0;account.lastLoginAt=Date.now();return{member:{...account.member},mustChangePassword:Boolean(account.credential.mustChangePassword)};}
export function changePassword(store,{mssv,currentPassword,newPassword,salt=null}={}){const id=String(mssv||'').trim(),account=store?.accounts?.get(id);if(!account)throw new Error('invalid_credentials');ensureCredential(account,currentPassword,store);if(!verifyCredential(account.credential,currentPassword))throw new Error('invalid_credentials');if(String(newPassword)===id)throw new Error('weak_password');account.credential=changeCredential(account.credential,newPassword,{salt,cost:store.options.cost||1024});account.initialCredentialPending=false;return{mssv:id,mustChangePassword:false,changedAt:account.credential.updatedAt};}
